### ISSUE TITLE
KeyError exception when parsing data from Allele Registry 

### ISSUE THREAD

**Issue by bryanwulf** [clingen-data-model/interpretation_json#3]
When parsing data from the Allele Registry, such as the response to the following request:
http://reg.genome.network/allele/CA658795130

an uncaught KeyError exception causes a crash:
>Traceback (most recent call last):
...
File "/var/task/clingen_interpretation/Allele.py", line 201, in __init__
results = get_car_hgvs_ctx_allele_dict(hgvs_38, ca_id)
File "/var/task/clingen_interpretation/Allele.py", line 93, in get_car_hgvs_ctx_allele_dict
external_recs = car_rep['externalRecords']
KeyError: 'externalRecords'

**Comment by bryanwulf** [comment]
Per a Slack discussion with Larry, it was decided that the solution was to no longer expect the `externalRecords` field in Allele Registry data (to treat it as optional).
